sudo: false
language: ruby
rvm:
  - 2.3.1

install:
  - bin/ci-prepare

script:
  - time bundle exec rake spec
  - bundle exec bundle-audit update
  - bundle exec bundle-audit check

deploy:
  provider: rubygems
  api_key:
    secure: "giuWhbgIbIDLQeO8RpWbaEj9llzLAYq27l/kPmTORCgkZjZV2clhZ4Z/bA+Ud9xNOrcUkJ5lLBFKrNDw2CIwBDC87sZsMRWE6QcO8uMnl20iRqrDYhPLa/dlfCMvsWZoC7Zqq/3AAiufrgOHSIP6X9Db0YVzGr4NejiKBX3f779ULqefqBjL+7OhbOCTLC80dlT2GkTf7j4Mz8aB5BK2W+XPY06/fMx+RGDz5gYPgcZcSoq2bDuYiG0BkF8nbbL3bq90guMSRrJ9uwSVhgb9TOJQdlA1Lk7pxbh39K/KC1H+pPePorWzk+vshxTDxr22GLLZBijan6hnwXzzIBWr8MGvFnSBVIGhOoU2DdPzmrl5iV1x9WAatPkgTQtTbiU0+CpGfHfv6D33GJ7eshCh9TMR3qZHySW+IFjCBFjKFooibIKL6y0zkzd95XYzBhka8k9R3YHMlG9DFNdpvrEVUcn5BQgld4GdCKkIK9GRCmOBvM+AEp+1qeg6Mmoy/WE6yHr1IloGUgiZwrbLhO8Qyzv4gvUTLrZxWIcshLnWQdyWhP990YTWW/mFFNz9arGUmtlJM6vUILLWHSBi4dOuMKTN69Ojc+H8MmqTn/Bg488GwSNhTgu7Sm1WSeg7rKKpHP7bu/b46xTb6t/skkF1tuCINy+W0hKC6U5jk9YrBCg="
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: always
