sudo: false
language: ruby
rvm:
  - 2.3.1

install:
  - bin/ci-prepare

script:
  - time bundle exec rake spec
  - bundle exec bundle-audit update
  - bundle exec bundle-audit check

deploy:
  provider: rubygems
  api_key:
    secure: N1Le4Ey5jPZFMKghclEDfAVpXusU9Qy5opngIa4JCDdl4zIX9L68LlEUdv/xaEQCODnTzDmT5E2eS8O2RwwrNhzioldUzvdwgN7ZCTotNXec94pEOaq/jEZivIxxLbr/avabR9IwAhgfFAEcFEZmOLZiQCY+VFX0WcoyOgLRM+MofTtJ/YlksULYbXNdZcdkdZZZz/36+NdA50LzaYwQTBbiRQWn0eEb5CKh4bz5uF+d20jQ5hj1MMH6WmXXo8LPN5zLvH6c6heujjIz+RzH8J3CyV9n4Cjwy3EYkmsaOJbEJBRHv2mrje9xyDyPbKAJVEtp4Z3ZRQM1siKgkvBWUNLOirWMnpeL8mwa7Z/7dauO8xluf8W1bUUDRpo9hevD1dYg1+h49dtt5yf++qijJpVFe/Uz40AWuomhTauWjfnWEkXa9113dno3Bwn0CApBiMgIse3m02dfQzbv6iyqtvPq5F+eIX1rx/xhy7Q2T8xYu9dDR7OSUBdW/xV4+eHjXMZEnwxYkhhEvE7liAtCq1dwE+fnYRpREvyYzeTdq1XAd0En9PaYqlhi6fWxY8fv1t4mHMuu9uY4zQnbF0A/2T5YJ3LMyMB09QrTRFTBh5yu9HqnBRgtmB6VacIjMKLR/VE+WIFB9qzlQqA9OMYJSEc3PKCA0KY3P4qbc1HOB9I=
    on:
    tags: true

notifications:
  email:
      on_success: change
      on_failure: always
